### ISSUE TITLE
Experimental splits for Cifar100, CUB and Caltech256

### ISSUE THREAD

**Issue by csyanbin** [tankche1/Semantic-Feature-Augmentation-in-Few-shot-Learning#6]
Hi, Zitian

I have read your paper "Semantic feature augmentation in few-shot learning".
This is really a wonderful idea with auto-encoder Trinet structure.

Could you release the train, val, test splits used in your experiments? 
Also, how many test data are used in meta-test phase?

Thanks so much!

**Comment by tankche1** [comment]
I release the data split in split.rar.
You can see the previous paper(maybe Matching Network) for the details of meta-test phase.

**Comment by csyanbin** [comment]
Thanks so much for the sharing!
